@startuml ER図
entity "User" {
    *user_id:bigint
    --
    *created:datetime
    *updated:datetime
    *subject_id:[FK(Subject, id)]
    *class:int
    *is_admin:bool
    *created_by:nvarchar(16)
    *updated_by:nvarchar(16)
}
entity "Subject" {
    *subject_id:int
    --
    *user_id:FK(User, id)
    *subject_name:nvarchar(20)
    *created:datetime
    *updated:datetime
    *created_by:nvarchar(16)
    *updated_by:nvarchar(16)
}
entity "FavoriteJobOffer" {
    *favorite_job_offer_id:int
    --
    *user_id:FK(User, id)
    *job_offer_id:FK(JobOffer, id)
    *created:datetime
    *updated:datetime
    *created_by:nvarchar(16)
    *updated_by:nvarchar(16)
}
entity "JobOffer" {
    *job_offer_id:int
    --
    *company_id:FK(Company, id)
    *occupation:nvarchar(40)
    *max_applicants:int
    *min_applicants:int
    *starting_salary:int
    *image_url:text
    *created:datetime
    *updated:datetime
    *created_by:nvarchar(16)
    *updated_by:nvarchar(16)
}
entity "Company" {
    *company_id:int
    --
    *company_name:nvarchar(40)
    *industry_id:FK(Industry, id)
    *postal_code:varchar(7)
    *created:datetime
    *updated:datetime
    *created_by:nvarchar(16)
    *updated_by:nvarchar(16)
}
entity "CompanyStreetAddress" {
    *company_street_address_id:int
    --
    *company_id:FK(Company, id)
    *street_address:text
    *is_main:bool
    *created:datetime
    *updated:datetime
    *created_by:nvarchar(16)
    *updated_by:nvarchar(16)
}
entity "Industry" {
    *industry_id:int
    --
    *industry_name:nvarchar(40)
    *created:datetime
    *updated:datetime
    *created_by:nvarchar(16)
    *updated_by:nvarchar(16)
}

CompanyStreetAddress }|--|| Company
Industry ||--o{ Company
User ||--o{ FavorateJobOffer
User }|--|| Subject
JobOffer ||--o{ FavorateJobOffer
JobOffer }o--|| Company

@enduml