version: "3.7"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ..:/workspace
    networks:
      - oicjob
    command: "sleep infinity"
  nginx:
    image: nginx
    ports:
      - "9876:9876"
    networks:
      - oicjob